services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       flux_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./flux-api
      dockerfile: Dockerfile
    image: flux-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Ativa o perfil “prod”
      SPRING_PROFILES_ACTIVE: prod

      # Resolve placeholders do CorsConfig:
      #DEFAULT_ACCESS_ORIGIN: "*"

      SPRING_DATASOURCE_URL:      jdbc:postgresql://postgres:5432/flux_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      timeout: 5s

  frontend:
    build:
      context: ./flux-frontend
      dockerfile: Dockerfile
    image: flux-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"


volumes:
  postgres_data:
