CREATE TABLE IF NOT EXISTS boards (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_boards_owner
    FOREIGN KEY(owner_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);
